# Generated by Django 5.1.2 on 2024-10-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurnitureApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_category', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_quantity', models.IntegerField(blank=True, null=True)),
                ('Product_price', models.IntegerField(blank=True, null=True)),
                ('Product_description', models.TextField(blank=True, max_length=300, null=True)),
                ('Product_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_manufactures', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_image1', models.ImageField(blank=True, null=True, upload_to='ProductImages')),
                ('Product_image2', models.ImageField(blank=True, null=True, upload_to='ProductImages')),
                ('Product_image3', models.ImageField(blank=True, null=True, upload_to='ProductImages')),
            ],
        ),
    ]
